FROM docker.io/library/golang:1.27-alpine AS build-img
COPY ./ /go/src/github.com/podman-container-tools/podman/
WORKDIR /go/src/github.com/podman-container-tools/podman
RUN go build -o /testvol ./test/testvol

FROM alpine
COPY --from=build-img /testvol /usr/local/bin
WORKDIR /
ENTRYPOINT ["/usr/local/bin/testvol", "serve"]
