---

name: validate renovate config

on:
  pull_request:
    paths:
      - .github/renovate.json5

permissions:
  contents: read

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Validate renovate config
        run: |
          docker run --rm \
              -v "$PWD/.github/renovate.json5:/usr/src/app/renovate.json5:ro" \
              ghcr.io/renovatebot/renovate:latest \
              renovate-config-validator
